spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys?serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
